server:
  address: { PRICE_RES_API_ADRRESS }
  shutdown: graceful
  port: 8080

spring:
  profiles:
    active: ${DEPLOY_ENV}
  main:
    allow-bean-definition-overriding: true
  application:
    name: price-rest-api
    env: ${ENVIRONMENT}
springfox:
  documentation:
    swagger:
      v2:
        enabled: true
  swagger-ui:
    enabled: true
    url: src/main/resources/spec/price-rest-api.yml

