server:
  address: { PRICE_REST_API_ADRRESS }
  shutdown: graceful
  port: 8080

spring:
  profiles:
    active: ${DEPLOY_ENV}
  main:
    allow-bean-definition-overriding: true
  application:
    name: price-rest-api
  datasource:
    url: jdbc:h2:mem:mydb
    username: ${USER_H2}
    password: ${PASSWORD_H2}
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always




