openapi: 3.0.3
info:
  title: Price Rest Api
  version: 1.0.0
paths:
  /price:
    get:
      summary: Get price of a product
      parameters:
        - name: applicationDate
          in: query
          description: Application date of the price
          schema:
            type: string
            format: date-time
            example: '2024-03-18T17:00:00'
          required: true
        - name: productId
          in: query
          description: Product identifier
          required: true
          schema:
            type: string
        - name: brandId
          in: query
          description: Brand identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request was successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '400':
          description: The request could not be understood by the server due to malformed syntax
          content:
            application/json:
              schema: { }
        '404':
          description: The requested resource was not found
          content:
            application/json:
              schema: { }
        '500':
          description: The server encountered an unexpected condition that prevented it from fulfilling the request
          content:
            application/json:
              schema: { }
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Product:
      required:
        - id
      type: object
      properties:
        id:
          description: product identifier
          type: string
          example: 35455
    Brand:
      description:
      type: string
      enum:
        - "1"
        - "2"
        - "3"
      x-enum-varnames:
        - ZARA
        - BRAND2
        - BRAND3
      example: "1"
    Currency:
      description: ISO currency
      type: string
      enum:
        - 978
        - 840
        - 826
      x-enum-varnames:
        - "EUR"
        - "USD"
        - "GBP"
      example: "978"
    PriceResponse:
      type: object
      properties:
        productId:
          description: product identifier
          type: string
          example: 35455
        brandId:
          description: brand identifier
          type: string
          example: 1
        priceList:
          type: string
          description: Identifier of the applicable price
          example: 3
        startDate:
          format: date-time
          type: string
          description: Start date
          example: '2024-03-18T17:00:00'
        endDate:
          format: date-time
          type: string
          description: End date
          example: '2024-03-18T17:00:00'
        price:
          type: double
          description: Final price to apply
          example: 15.45
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string